[32m2024-07-09 16:21:40 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a37e4b00-42fe-4289-8203-fa1927f8a46c - 16026 - LOGS_CAPTURED - Started capturing logs in process (pid: 16026).
[32m2024-07-09 16:21:40 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a37e4b00-42fe-4289-8203-fa1927f8a46c - 16026 - FMC_UPD_RUN_STATUS_FL_SLS - STEP_START - Started execution of step "FMC_UPD_RUN_STATUS_FL_SLS".
[32m2024-07-09 16:21:40 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - a37e4b00-42fe-4289-8203-fa1927f8a46c - FMC_UPD_RUN_STATUS_FL_SLS - Executing query: 
        CALL SPEEDSHOP_PROC.SET_FMC_MTD_FL_INIT_SLS('100', '1');
    
[32m2024-07-09 16:21:40 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a37e4b00-42fe-4289-8203-fa1927f8a46c - 16026 - FMC_UPD_RUN_STATUS_FL_SLS - STEP_FAILURE - Execution of step "FMC_UPD_RUN_STATUS_FL_SLS" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "FMC_UPD_RUN_STATUS_FL_SLS"::

snowflake.connector.errors.ProgrammingError: 001044 (42P13): SQL compilation error: error line 0 at position -1
Invalid argument types for function 'SET_FMC_MTD_FL_INIT_SLS': (VARCHAR(3), VARCHAR(1))

Stack Trace:
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/Documents/GitHub/quickstart-snowflake-fix-fast-deploys/quickstart_snowflake/assets/init_sales.py", line 959, in FMC_UPD_RUN_STATUS_FL_SLS
    cursor.execute(query)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
[0m
